spring:
  application:
    name: orderservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Order Service version 1.0
server:
  port: 20192